### ISSUE TITLE
missing field `coinbase` `startL1QueueIndex`

### ISSUE THREAD

**Issue by daydaybetter** [scroll-tech/scroll-prover#226]
When I use the latest code to run chunk_tests, it failed. How to get the correct traces file to solve this error?

`test test_chunk_prove_verify ... FAILED

failures:

---- test_chunk_prove_verify stdout ----
thread 'test_chunk_prove_verify' panicked at 'unable to load BlockTrace from "./tests/traces/erc20/10_transfer.json", Error("missing field `coinbase`", line: 69137, column: 1), Error("missing field `startL1QueueIndex`", line: 69136, column: 3)', prover/src/utils.rs:87:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/panicking.rs:64:14
   2: prover::utils::get_block_trace_from_file
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: prover::test_util::load_block_traces_for_test
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_chunk_prove_verify

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass `-p prover --test chunk_tests``

**Comment by silathdiir** [comment]
The traces are outdated. We will provide new traces later.

**Comment by daydaybetter** [comment]
Thanks!
