### ISSUE TITLE
thread 'test_chunk_prove_verify' panicked at 'called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by ebaizel** [scroll-tech/scroll-prover#284]
I am running `make test-chunk-prove` and running into this error during the tests:

`thread 'test_chunk_prove_verify' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ubuntu/.cargo/git/checkouts/snark-verifier-cd02c9c9f799657f/bc1d39a/snark-verifier/src/loader/evm/util.rs:115:10`

Please let me know if there are any other logs or artifacts I can include that would help to debug.

Here is the full stack trace:

```
Context "Range" used 1 advice columns and 9169285 total advice cells in phase 0
Special lookup advice cells: optimal columns: 1, total 1002822 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 300577
computing length 37 fixed base msm
computing length 38 MSM
computing length 1 MSM
computing length 1 MSM
Context "Range" used 1 advice columns and 9169285 total advice cells in phase 0
Special lookup advice cells: optimal columns: 1, total 1002822 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 300577
thread 'test_chunk_prove_verify' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ubuntu/.cargo/git/checkouts/snark-verifier-cd02c9c9f799657f/bc1d39a/snark-verifier/src/loader/evm/util.rs:115:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/result.rs:1791:5
   3: snark_verifier::loader::evm::util::compile_yul
   4: snark_verifier_sdk::evm_api::gen_evm_verifier
   5: prover::common::verifier::evm::<impl prover::common::verifier::Verifier<C>>::evm_verify
   6: integration::test_util::proof::gen_and_verify_normal_and_evm_proofs
   7: integration::test_util::proof::gen_and_verify_chunk_proofs
   8: core::ops::function::FnOnce::call_once
   9: core::ops::function::FnOnce::call_once
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_chunk_prove_verify

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5289.95s
```

**Comment by silathdiir** [comment]
Need to install `solc` `0.8.19` as https://github.com/scroll-tech/scroll-prover/pull/285.

**Comment by ebaizel** [comment]
That did it, thanks!
