### ISSUE TITLE
test-batch-prove missing field `tx_bytes`

### ISSUE THREAD

**Issue by wanghs09** [scroll-tech/scroll-prover#325]
tag `v0.10.3`
`make test-batch-prove`

Error
```
---- test_batch_prove_verify stdout ----
thread 'test_batch_prove_verify' panicked at integration/tests/batch_tests.rs:52:76:
called `Result::unwrap()` on an `Err` value: missing field `tx_bytes` at line 10 column 5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90e321d82a0a9c3d0e3f180d4d17541b729072e0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/90e321d82a0a9c3d0e3f180d4d17541b729072e0/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/90e321d82a0a9c3d0e3f180d4d17541b729072e0/library/core/src/result.rs:1649:5
   3: batch_tests::load_chunk_hashes_and_proofs
   4: core::ops::function::FnOnce::call_once
   5: core::ops::function::FnOnce::call_once
             at /rustc/90e321d82a0a9c3d0e3f180d4d17541b729072e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by Thegaram** [comment]
Thanks for reporting this! This test is currently not maintained.
